//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Article
    {
        public System.Guid articleId { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public string content { get; set; }
        public System.Guid memberId { get; set; }
        public string meta { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
    
        public virtual Member Member { get; set; }
    }
}
