//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web.Mvc;

    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Articles = new HashSet<Article>();
            this.Invoinces = new HashSet<Invoince>();
            this.Products = new HashSet<Product>();
        }
    
        public System.Guid memberId { get; set; }
        [DisplayName("Số điện thoại")]
        public string phone { get; set; }
        public string password { get; set; }
        [DisplayName("Tên")]
        public string firstName { get; set; }
        [DisplayName("Họ")]
        public string lastName { get; set; }
        [DisplayName("Email")]
        public string email { get; set; }
        [DisplayName("Ngày sinh")]
        public Nullable<System.DateTime> birthday { get; set; }
        [DisplayName("Địa chỉ")]
        public string address { get; set; }
        public string avatar { get; set; }
        public System.Guid roleId { get; set; }
        public string meta { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Article> Articles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoince> Invoinces { get; set; }
        public virtual Role Role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Products { get; set; }
    }
}
