//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Variant
    {
        public System.Guid productId { get; set; }
        public System.Guid sizeId { get; set; }
        public System.Guid colorId { get; set; }
        public string sku { get; set; }
        public Nullable<int> cost { get; set; }
        public int quantity { get; set; }
        public string image { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> dateCreate { get; set; }
    
        public virtual Color Color { get; set; }
        public virtual Product Product { get; set; }
        public virtual Size Size { get; set; }
    }
}
